"""Rebuild assets/, fonts/, and notes/assets.md from the talk's asset staging folder.

Usage:  <staging>/_tools/venv/bin/python -I tools/build-assets.py <staging dir>
The staging dir holds CATALOG.md and _tools/manifest.tsv (file, commit, source path).
"""
import base64
import re
import sys
from pathlib import Path

from PIL import Image

deck = Path(__file__).resolve().parent.parent
staging = Path(sys.argv[1]).resolve()
out = deck / "assets"
fonts = deck / "fonts"
out.mkdir(exist_ok=True)
fonts.mkdir(exist_ok=True)

css = (staging / "input-block-prototypes/fonts.inc.css").read_text()
for family, data in re.findall(r"font-family: '([^']+)';.*?base64,([A-Za-z0-9+/=]+)", css, re.S):
    (fonts / (family.replace(" ", "") + ".woff2")).write_bytes(base64.b64decode(data))

SESSION = "SessionViewVisualTests--seededSessionViewMatchesVisualBaseline"
APP_SCREEN = (0, 440, 1206, 2622)
PROTO_SCREEN = (0, 170, 1179, 2440)
PROTO_CARD = (0, 1060, 1179, 2330)
GALLERY = [
    "session-stage-a", "session-stage-d", "input-block3-c", "superset-stage4-a", "superset-stage4-c",
    "block-grid-focus4-d-6d", "exercise-history6-b", "sunbird-moments-c", "sunbird-moments-a", "sunbird-moments-d",
]

# name: (staging file, crop box, output width, role chip, slides)
JOBS = {
    "today-day.webp": (f"current-app/{SESSION}.1.png", APP_SCREEN, 760, "APP RENDER · 7fefd137", "1, 13"),
    "today-night.webp": (f"current-app/SessionViewVisualTests--seededSessionViewMatchesNightVisualBaseline.1.png", APP_SCREEN, 760, "APP RENDER · 7fefd137", "1"),
    "old-session.webp": (f"old-app/{SESSION}.1.png", APP_SCREEN, 760, "APP RENDER · 9c90b127", "2, 5, 13"),
    "first-build-session.webp": (f"failed-implementation/{SESSION}-day.1.png", APP_SCREEN, 760, "AUDIT RENDER of PR #467 · 56848626", "13"),
    "first-build-card.webp": (f"failed-implementation/{SESSION}-day.1.png", (40, 1210, 1170, 1770), 760, "AUDIT RENDER of PR #467 · 56848626", "14"),
    "pick-screen.webp": ("accepted-prototypes/input-block3-c.png", PROTO_SCREEN, 760, "PROTOTYPE · accepted pick", "9, 13"),
    "pick-card.webp": ("accepted-prototypes/input-block3-c.png", (80, 1370, 1100, 2280), 760, "PROTOTYPE · accepted pick", "16"),
    "today-card.webp": ("current-app/ActiveSetCardVisualTests--activeSetCardMatchesVisualBaseline.1.png", (40, 870, 1170, 1830), 760, "APP RENDER · Active Set Card fixture · 7fefd137", "16"),
    "wt-dev-icon.webp": ("brand/AppIconDev-Icon-1024.png", None, 240, "real WT Dev icon inside RECONSTRUCTION · drawn for this talk", "7"),
    "ib-p.webp": ("input-block-prototypes/input-block-p.png", (0, 700, 1179, 1970), 520, "PRODUCTION · redrawn in HTML", "9"),
    **{f"ib1-{v}.webp": (f"input-block-prototypes/input-block-{v}.png", PROTO_CARD, 520, "PROTOTYPE · browser render", "9") for v in "abcde"},
    **{f"ib2-{v}.webp": (f"input-block-prototypes/input-block2-{v}.png", PROTO_CARD, 520, "PROTOTYPE · browser render", "9") for v in "abcd"},
    **{f"ib3-{v}.webp": (f"input-block-prototypes/input-block3-{v}.png", PROTO_CARD, 520, "PROTOTYPE · browser render", "9") for v in "abcd"},
    **{f"pick-{g}.webp": (f"accepted-prototypes/{g}.png", PROTO_SCREEN, 420, "PROTOTYPE · accepted pick", "10") for g in GALLERY},
}

manifest = {}
for line in (staging / "_tools/manifest.tsv").read_text().splitlines():
    file, commit, path = line.split("\t")
    manifest[file] = f"{path}@{commit[:8]}"

for stale in out.glob("*.webp"):
    if stale.name not in JOBS:
        stale.unlink()

rows = []
for name, (src, box, width, role, slides) in JOBS.items():
    im = Image.open(staging / src).convert("RGB")
    if box:
        im = im.crop(box)
    im = im.resize((width, round(im.height * width / im.width)), Image.LANCZOS)
    im.save(out / name, quality=92, method=6)
    rows.append(f"| `assets/{name}` | `{src}` | `{manifest[src]}` | {role} | {slides} |")
    print(name, im.size)

(deck / "notes/assets.md").write_text(
    "# Assets\n\n"
    "Generated by `tools/build-assets.py` from the asset staging folder (see its `CATALOG.md`). "
    "Each WebP is a crop of one staged file, saved at quality 92. Do not edit by hand; rerun the script.\n\n"
    "| Asset | Staging file | Source path@commit | Role chip on the slide | Slides |\n"
    "| --- | --- | --- | --- | --- |\n" + "\n".join(rows) + "\n"
)
