"""Side-by-side Python orchestrator for Ralph.

This package owns the deterministic workflow state described in
``docs/specs/2026-06-05-ralph-python-pr-orchestrator.md``. Agent engines only
own individual phase turns; Python owns selection, routing, gates, authority
policies, and PR-only publication.

The shell runner ``ralph/ralph.sh`` remains the production path until the
replacement gate in issue #214 is approved.
"""

from __future__ import annotations

from .authority import (
    UI_REVIEW_PASS_LINE,
    VISUAL_BASELINE_DIR,
    AuthorityDecision,
    AuthorityGate,
    NameStatusEntry,
)
from .blocked import (
    MAX_EXCERPT_BYTES,
    MAX_EXCERPT_LINES,
    REDACTION_PLACEHOLDER,
    BlockedReport,
    BlockedReportWriter,
    BlockedRescuePlan,
    BlockedRescuePublisher,
    blocked_branch,
    blocked_commit_message,
    blocked_pr_title,
    cap_excerpt,
    redact_secrets,
)
from .config import ConfigError, RunConfig, parse_args
from .contracts import (
    IssueComment,
    IssueContract,
    capture_issue_contract,
    parse_prd_number,
    parse_ui_test_authorization,
)
from .engine import Engine, FakeEngine, PhaseRequest, build_engine
from .engines import (
    CLAUDE_CLI_ENGINE,
    CLAUDE_SDK_ENGINE,
    CODEX_CLI_ENGINE,
    CODEX_SDK_ENGINE,
    TIMEOUT_EXIT_STATUS,
    ClaudeCliEngine,
    ClaudeSdkEngine,
    CliInvocation,
    CliResult,
    CodexCliEngine,
    CodexSdkEngine,
    SdkEvent,
    SdkInvocation,
    blocked_promise_prefix,
    complete_promise_line,
    default_cli_runner,
    normalize_sdk_events,
    parse_promise,
    resolve_engine,
)
from .gates import (
    CommandResult,
    GateResult,
    GateRunner,
    GateSpec,
    GateStatus,
    is_ui_owned_gate,
)
from .github import (
    FakeGitHubClient,
    GhCliClient,
    GitHubClient,
    GitHubClientError,
)
from .phase import PhaseResult, PhaseStatus
from .prompt_context import (
    BLOCKED_REPORT_FILE,
    GATE_FAILURE_SUMMARY_FILE,
    ISSUE_CONTRACT_FILE,
    PHASE_CONTEXT_FILE,
    REPAIR_BRIEF_FILE,
    PhaseContext,
    PromptContextWriter,
    render_gate_failure_summary,
    render_issue_contract,
    render_phase_context,
)
from .publish import (
    LABEL_AGENT_BLOCKED,
    LABEL_AGENT_IMPLEMENTED,
    LABEL_AGENT_READY_FOR_REVIEW,
    LABEL_READY_FOR_AGENT,
    LABEL_READY_FOR_HUMAN,
    GitOutcome,
    IssuePublisher,
    PublishError,
    PullRequestPublisher,
    integration_commit_message,
)
from .repair import (
    DEFAULT_PHASE_TIMEOUT_SECONDS,
    PHASE_REPAIR_UI_GATE,
    PHASE_SWIFT_REVIEW_AFTER_REPAIR,
    RepairCoordinator,
    RepairError,
    RepairOutcome,
    render_repair_brief,
    repair_brief_relpath,
    requires_swift_review,
)
from .targets import PrTarget, TargetResolutionError, TargetResolver, branch_for_contract
from .worktree import (
    GitResult,
    Worktree,
    WorktreeError,
    WorktreeManager,
    default_git_runner,
)

__all__ = [
    "BLOCKED_REPORT_FILE",
    "CLAUDE_CLI_ENGINE",
    "CLAUDE_SDK_ENGINE",
    "CODEX_CLI_ENGINE",
    "CODEX_SDK_ENGINE",
    "GATE_FAILURE_SUMMARY_FILE",
    "ISSUE_CONTRACT_FILE",
    "LABEL_AGENT_BLOCKED",
    "LABEL_AGENT_IMPLEMENTED",
    "LABEL_AGENT_READY_FOR_REVIEW",
    "LABEL_READY_FOR_AGENT",
    "LABEL_READY_FOR_HUMAN",
    "MAX_EXCERPT_BYTES",
    "MAX_EXCERPT_LINES",
    "PHASE_CONTEXT_FILE",
    "REDACTION_PLACEHOLDER",
    "REPAIR_BRIEF_FILE",
    "TIMEOUT_EXIT_STATUS",
    "UI_REVIEW_PASS_LINE",
    "VISUAL_BASELINE_DIR",
    "AuthorityDecision",
    "AuthorityGate",
    "DEFAULT_PHASE_TIMEOUT_SECONDS",
    "PHASE_REPAIR_UI_GATE",
    "PHASE_SWIFT_REVIEW_AFTER_REPAIR",
    "BlockedReport",
    "BlockedReportWriter",
    "BlockedRescuePlan",
    "BlockedRescuePublisher",
    "ClaudeCliEngine",
    "ClaudeSdkEngine",
    "CliInvocation",
    "CliResult",
    "CodexCliEngine",
    "CodexSdkEngine",
    "CommandResult",
    "ConfigError",
    "Engine",
    "FakeEngine",
    "FakeGitHubClient",
    "GateResult",
    "GateRunner",
    "GateSpec",
    "GateStatus",
    "GhCliClient",
    "GitHubClient",
    "GitHubClientError",
    "GitOutcome",
    "GitResult",
    "IssueComment",
    "IssueContract",
    "IssuePublisher",
    "NameStatusEntry",
    "PhaseContext",
    "PhaseRequest",
    "PhaseResult",
    "PhaseStatus",
    "PrTarget",
    "PromptContextWriter",
    "PublishError",
    "PullRequestPublisher",
    "RepairCoordinator",
    "RepairError",
    "RepairOutcome",
    "RunConfig",
    "SdkEvent",
    "SdkInvocation",
    "TargetResolutionError",
    "TargetResolver",
    "Worktree",
    "WorktreeError",
    "WorktreeManager",
    "blocked_branch",
    "blocked_commit_message",
    "blocked_pr_title",
    "blocked_promise_prefix",
    "branch_for_contract",
    "build_engine",
    "cap_excerpt",
    "capture_issue_contract",
    "complete_promise_line",
    "default_cli_runner",
    "default_git_runner",
    "integration_commit_message",
    "is_ui_owned_gate",
    "normalize_sdk_events",
    "parse_args",
    "parse_prd_number",
    "parse_promise",
    "parse_ui_test_authorization",
    "redact_secrets",
    "render_gate_failure_summary",
    "render_issue_contract",
    "render_phase_context",
    "render_repair_brief",
    "repair_brief_relpath",
    "requires_swift_review",
    "resolve_engine",
]
